"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py build_ext --inplace py2app
    python setup.py bdist bdist_wheel py2app
"""

from setuptools import setup
# from Cython.Build import cythonize
# from Cython.Distutils import build_ext


setup(
    name='asmbattle',
    version='0.9.1',
    author='Michel Rondeau',
    author_email='mr@michelrondeau.com',
    url='https:://www.asmblattle.com',
    description='simple assembler code training and game',
    long_description=open("README.md").read(),
    # packages = ['asmbattle'],
    classifiers=[
        'Development Status :: 2 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.9'
    ],
    # Include additional files into the package using MANIFEST.in
    include_package_data=True,
    app= ['asmbattle/__main__.py'],
    # data_files=["./locale/*", "./ASM/*"],
    package_data={'locale': ['*.mo', '*.po', '*.pot'],
                  'ASM': ['*.asm']},
#     cmdclass = {'build_ext': build_ext},
#     ext_modules = cythonize(["asmbattle/opcodes.py",
#                              "asmbattle/assembler.py",
#                              "asmbattle/cpu.py",
#                              "asmbattle/memory.py",
#                              "asmbattle/ui_controller.py",
#                              "asmbattle/ui_view.py",
#                              "asmbattle/aboutbox.py"], language_level=3),

    keywords='assembler programing game',
    setup_requires=['py2app'],
    options={'py2app': {'iconfile': "resources/asmbattle.icns"}}, #  , 'cython': {"language_level":"3"}},
    install_requires=[
        "pillow", "markdown", "tk_html_widgets"
    ],
    entry_points={
        "gui_scripts": [
            "asmbattle = asmbattle.__main__:main"
        ]
    },
)
